# Generated by Django 5.1.5 on 2025-02-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_timeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking.timeslot",
            ),
        ),
    ]
